replicaCount: 1

image:
  repository: ncdocker.netconomy.net/tls/jassistant
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
    - jassistant.company.com

resources: {}
  limits:
   cpu: 500m
   memory: 2000Mi
  requests:
   cpu: 200m
   memory: 1000Mi

nodeSelector: {}

tolerations: []

affinity: {}
